repos:
-   repo: https://github.com/frnmst/md-toc
    rev: 8.0.1  # or a specific git tag from md-toc
    hooks:
    -   id: md-toc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
