[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "python-lsp-server",
    "python-lsp-black",
    "python-lsp-isort",
    "pylsp-mypy",
    "md-toc",
    "pre-commit",
    "pylint",
    "mypy",
    "ipython",
    "pyhamcrest",
    "pytest",
    "types-requests>=2.31.0.20240406",
]

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = [
    {name = "David James McCorrie", email = "djmccorrie@gmail.com"},
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "data-science-types",
    "black",
    "click",
    "types-requests",
    "requests",
]
name = "abm-tools"
version = "0.1.1"
description = "Provides Tools to generate Aramaic bible software modules such as SWORD, MySWORD, E-SWORD modules"
readme = "README.md"

[project.scripts]
abm-tools = "abm_tools.cli:cli"
