[tool.poetry]
name = "abm-tools"
version = "0.1.0"
description = "Provides Tools to generate Aramaic bible software modules such as SWORD, MySWORD, E-SWORD modules"
license = "Apache-2.0"
authors = ["David James McCorrie <djmccorrie@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
md-toc = "^7.0.5"
pre-commit = "^2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pyhamcrest = "^2.0.2"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
